# This is a basic workflow to help you get started with Actions

name: Build Latest NKH

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        name: Checkout Code
        
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        
      - uses: nuget/setup-nuget@v1
        name: Setup Nuget
        
      - name: Checkout submodules
        run: git submodule update --init --recursive
        
      - name: Delete unused NLayer projects
        run: rd /S /Q %CD%\NKHook6\NKHook6\Dependencies\NLayer\NLayer.NAudioSupport | rd /S /Q %CD%\NKHook6\NKHook6\Dependencies\NLayer\TestApp
        
      - name: Restore NuGet Packages
        run: nuget restore SimpleFrameworkApp.sln

      - name: Build NKHook6
        run: msbuild NKHook6/NKHook6.sln /p:Configuration=Release
        
      - uses: actions/upload-artifact@v2
        with:
          name: NKHook6-Build
          path: NKHook6\NKHook6\bin\Release\NKHook6.dll
